# EnderDragonTweaks - Ender Dragon tweaks, mainly for SMP servers
# by EvsDev (https://github.com/evs-dev)
# contributors: https://github.com/evs-dev/EnderDragonTweaks/graphs/contributors
# CONFIGURATION FILE
# ❗ IMPORTANT INFO: ❗
# - All text supports using the ampersand (&) symbol for colours and formats
#   (https://minecraft.fandom.com/wiki/Formatting_codes#Color_codes)
# - Placeholders can be included in strings and are replaced by the plugin
# - Every string that has placeholders has a comment above explaining them
# - You can use any statistic from statistics.yml as a placeholder, e.g. <stat-dragonDeathCount>
# - Every string requires quotes ("example string") unless the default does not have them
# - 20 ticks = 1 second
# - This plugin uses bStats. To opt out of its anonymous stats collection,
#   find the bStats folder in your plugins folder and set enabled to false in its config
#   (https://bstats.org/plugin/bukkit/EnderDragonTweaks/12284)

# Config version - DO NOT CHANGE (is set by plugin)
version: 0

# Is the plugin enabled?
# DEFAULT: true
enabled: true


# |------------------------|
# |        Features        |
# |------------------------|

egg-respawn:
  enabled: true

  # The coordinates of the Dragon egg when it spawns
  # DEFAULT: 0, 0, 0 (this does not need to be configured by default since the portal coordinates are always (0, 0))
  position:
    x: 0
    y: 0
    z: 0
    # Should the y coordinate specified here dictate exactly where the Dragon egg should go?
    # If false, the plugin will try to find an air block above a bedrock block
    # DEFAULT: false
    override-y: false
